/**
 * Core interface definition representing the standard Book domain model entity.
 */
export interface Book {
  /** The unique identifier generated by the backend infrastructure. */
  id: string;
  /** The primary title or name of the book. */
  title: string;
  /** The full name or pseudonym of the book's author. */
  author: string;
  /** The calendar year the book was published, represented as a string. */
  year: string;
  /** A detailed summary, synopsis, or editorial review of the book content. */
  description: string;
  /** A fully qualified URL pointing to the hosted cover image asset. */
  coverImage: string;
  /** Indicates whether the current user has marked this book as a favorite. */
  isFavorite: boolean;
  /** The ISO 8601 timestamp indicating when the record was initially injected. */
  createdAt: string;
  /** The ISO 8601 timestamp tracking the most recent differential update. */
  updatedAt: string;
}

/**
 * Global blueprint for any data transfer object used to create or fully replace a book entity.
 * Strips away server-managed systemic properties like id and analytical timestamps.
 */
export type BookPayload = Omit<Book, 'id' | 'createdAt' | 'updatedAt'>;
