/**
 * Core interface definition representing the standard Book domain model entity.
 * Serves as the central immutable enterprise data contract across the entire application ecosystem.
 */
export interface Book {
  /** The unique identifier generated by the backend infrastructure */
  readonly bookId: string;
  /** The primary title or name of the book */
  readonly title: string;
  /** The full name or pseudonym of the book's author */
  readonly author: string;
  /** The specific historical calendar year the book was written, represented as a string */
  readonly writingYear: string;
  /** A detailed summary, synopsis, or editorial review of the book content */
  readonly description: string;
  /** A fully qualified URL pointing to the hosted cover image asset */
  readonly coverImage: string;
  /** Indicates whether the current user has marked this book as a favorite */
  readonly isFavorite: boolean;
  /** The ISO 8601 timestamp indicating when the record was initially injected */
  readonly createdAt: string;
  /** The ISO 8601 timestamp tracking the most recent differential update */
  readonly updatedAt: string;
}

/**
 * Global blueprint for any data transfer object used to create or fully replace a book entity.
 * Strips away server-managed systemic properties like bookId and analytical timestamps.
 */
export type BookPayload = Omit<Book, 'bookId' | 'createdAt' | 'updatedAt'>;
