import { SNACKS } from '../constants/snackConstants';

/**
 * Compile-time union type extracted directly from runtime SNACKS constants.
 * Resolves strictly to explicitly permitted severity notification categories.
 * Controls visual theme vector selections and icon color mappings down the layout tree.
 */
export type Snack = (typeof SNACKS)[keyof typeof SNACKS];

/**
 * Structural contract representing a singular instantiated snack message metadata layer.
 * Tracks unique identities and timer configurations for state stack operations.
 */
export interface SnackItem {
  /** The unique identifier generated by infrastructure utilities for stack clearing */
  readonly id: string;
  /** The text string content visible to the user inside the alert box */
  readonly message: string;
  /** The specific severity class style token routing color palettes */
  readonly type: Snack;
}
